// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Message = __t.object("Message", {
  id: __t.u64(),
  sender: __t.string(),
  text: __t.string(),
  sentAt: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

